let Blogsdb = [
    {
        id: 1,
        Details: { Author: "Puzzles Plan",  Released: "June 2025",  Credits: "Images from puzzlesplan website"},
        title: "Play Jigsaw Planet Free on Puzzlesplan",
        description:
            "Explore unique jigsaw planet games at puzzlesplan – your hub for fun and entertainment.",
        category: "Puzzlesplan . Jigsaw Games . Fun",
        image: "./images/nightshift.webp",
    },
    {
        id: 2,
        Details: { Author: "Puzzles Plan", Released: "June 2025", Credits: "Images from puzzlesplan website" },
        title: "Top Jigsawplanet Game Picks on Puzzlesplan",
        description: "Puzzlesplan offers free jigsawplanet puzzles with exciting gameplay and variety.",
        category: "Puzzlesplan . Puzzle Games . Entertainment",
        image: "./images/beautifulplace.webp",
    },
    {
        id: 3,
        Details: { Author: "Puzzles Plan", Released: "June 2025", Credits: "Images from puzzlesplan website" },
        title: "Puzzlesplan Jigsawplanet Games Collection",
        description: "Discover the best jigsawplanet games online at puzzlesplan, made for puzzle lovers.",
        category: "Puzzlesplan . Puzzle Gaming . Fun",
        image: "./images/darkhistory.webp",
    },
    {
        id: 4,
        Details: { Author: "Puzzles Plan", Released: "June 2025", Credits: "Images from puzzlesplan website" },
        title: "Jigsaw Puzzle Fun with Puzzlesplan",
        description: "Play top-rated jigsaw puzzles at puzzlesplan – where puzzle fun begins.",
        category: "Puzzlesplan . Jigsaw . Fun Games",
        image: "./images/jigsawsnow.webp",
    },
    {
        id: 5,
        Details: { Author: "Puzzles Plan", Released: "June 2025", Credits: "Images from puzzlesplan website" },
        title: "Freeze Nova Puzzles at Puzzlesplan",
        description: "Explore the best of Freezenova games, now featured on puzzlesplan.com.",
        category: "Puzzlesplan . Freezenova Games . Entertainment",
        image: "./images/jigsawengine.webp",
    },
    {
        id: 6,
        Details: { Author: "Puzzles Plan", Released: "June 2025", Credits: "Images from puzzlesplan website" },
        title: "Free Puzzlesplan Jigsawplanet Games",
        description: "Play free puzzles from jigsawplanet on puzzlesplan and challenge your brain.",
        category: "Puzzlesplan . Free Games . Jigsawplanet",
        image: "./images/eiffeltower.webp",
    },
    {
        id: 7,
        Details: { Author: "Puzzles Plan", Released: "June 2025", Credits: "Images from puzzlesplan website" },
        title: "Play Free Jigsaw Games on Puzzlesplan",
        description: "Enjoy interactive jigsaw games online with puzzlesplan’s fun puzzle collection.",
        category: "Puzzlesplan . Free Jigsaw . Puzzle Games",
        image: "./images/treeriver.webp",
    },
    {
        id: 8,
        Details: { Author: "Puzzles Plan", Released: "June 2025", Credits: "Images from puzzlesplan website" },
        title: "Jigsawplanet Challenges on Puzzlesplan",
        description: "Join the puzzlesplan community and solve unique jigsawplanet puzzles today.",
        category: "Puzzlesplan . Jigsawplanet Fun . Games",
        image: "./images/Freezenova4.jpeg",
    },
    {
        id: 9,
        Details: { Author: "Puzzles Plan", Released: "June 2025", Credits: "Images from puzzlesplan website" },
        title: "Free Jigsaw Games by Puzzlesplan",
        description: "Access a growing library of jigsaw games online, curated by puzzlesplan experts.",
        category: "Puzzlesplan . Jigsaw Games . Free Puzzles",
        image: "./images/Freezenova5.jpeg",
    },
    {
        id: 10,
        Details: { Author: "Puzzles Plan", Released: "June 2025", Credits: "Images from puzzlesplan website" },
        title: "Puzzlesplan Presents Freezenova Games",
        description: "Play the most engaging Freezenova jigsaw puzzles right on puzzlesplan.",
        category: "Puzzlesplan . Freezenova . Puzzle Fun",
        image: "./images/Freezenova6.jpeg",
    },
    {
        id: 11,
        Details: { Author: "Puzzles Plan", Released: "June 2025", Credits: "Images from puzzlesplan website" },
        title: "Explore Jigsaw Planet on Puzzlesplan",
        description: "Join thousands playing puzzle games at puzzlesplan featuring jigsaw planet hits.",
        category: "Puzzlesplan . Jigsawplanet . Game Hub",
        image: "./images/Freezenova7.jpeg",
    },
    {
        id: 12,
        Details: { Author: "Puzzles Plan", Released: "June 2025", Credits: "Images from puzzlesplan website" },
        title: "Jigsaw Planet Games by Puzzlesplan",
        description: "Solve relaxing and challenging jigsaw puzzles from puzzlesplan’s top selections.",
        category: "Puzzlesplan . Jigsawplanet . Relax & Play",
        image: "./images/Freezenova8.jpeg",
    },
];

export default Blogsdb;
