let Blogsdb = [
    {
        id: 1,
        Details: { Author: "Puzzles Plan", Released: "September 2025", Credits: "Images from puzzlesplan website" },
        title: "Play Free Jigsaw Puzzles on Puzzlesplan",
        description:
            "Explore unique free jigsaw puzzle games at puzzlesplan – your hub for fun and entertainment.",
        category: "Puzzlesplan . Jigsaw Games . Fun",
        image: "./images/nightshift.webp",
    },
    {
        id: 2,
        Details: { Author: "Puzzles Plan", Released: "September 2025", Credits: "Images from puzzlesplan website" },
        title: "Top Free Jigsaw Puzzle Picks on Puzzlesplan",
        description: "Puzzlesplan offers free jigsaw puzzle games with exciting gameplay and variety.",
        category: "Puzzlesplan . Puzzle Games . Entertainment",
        image: "./images/beautifulplace.webp",
    },
    {
        id: 3,
        Details: { Author: "Puzzles Plan", Released: "September 2025", Credits: "Images from puzzlesplan website" },
        title: "Puzzlesplan Online Puzzle Games Collection",
        description: "Discover the best free puzzle games online at puzzlesplan, made for puzzle lovers.",
        category: "Puzzlesplan . Puzzle Gaming . Fun",
        image: "./images/darkhistory.webp",
    },
    {
        id: 4,
        Details: { Author: "Puzzles Plan", Released: "September 2025", Credits: "Images from puzzlesplan website" },
        title: "Jigsaw Puzzle Fun with Puzzlesplan",
        description: "Play top-rated online jigsaw puzzles at puzzlesplan – where puzzle fun begins.",
        category: "Puzzlesplan . Jigsaw . Fun Games",
        image: "./images/jigsawsnow.webp",
    },
    {
        id: 5,
        Details: { Author: "Puzzles Plan", Released: "September 2025", Credits: "Images from puzzlesplan website" },
        title: "Freeze Nova Puzzles at Puzzlesplan",
        description: "Explore the best Freezenova games, now featured on puzzlesplan.com.",
        category: "Puzzlesplan . Freezenova Games . Entertainment",
        image: "./images/jigsawengine.webp",
    },
    {
        id: 6,
        Details: { Author: "Puzzles Plan", Released: "September 2025", Credits: "Images from puzzlesplan website" },
        title: "Free Online Puzzles on Puzzlesplan",
        description: "Play free puzzles on puzzlesplan and challenge your brain with interactive fun.",
        category: "Puzzlesplan . Free Games . Online Puzzles",
        image: "./images/eiffeltower.webp",
    },
    {
        id: 7,
        Details: { Author: "Puzzles Plan", Released: "September 2025", Credits: "Images from puzzlesplan website" },
        title: "Play Free Jigsaw Games on Puzzlesplan",
        description: "Enjoy interactive online jigsaw games with puzzlesplan’s fun puzzle collection.",
        category: "Puzzlesplan . Free Jigsaw . Puzzle Games",
        image: "./images/treeriver.webp",
    },
    {
        id: 8,
        Details: { Author: "Puzzles Plan", Released: "September 2025", Credits: "Images from puzzlesplan website" },
        title: "Puzzle Challenges on Puzzlesplan",
        description: "Join the puzzlesplan community and solve unique online puzzle challenges today.",
        category: "Puzzlesplan . Puzzle Challenges . Games",
        image: "./images/Freezenova4.jpeg",
    },
    {
        id: 9,
        Details: { Author: "Puzzles Plan", Released: "September 2025", Credits: "Images from puzzlesplan website" },
        title: "Free Jigsaw Games by Puzzlesplan",
        description: "Access a growing library of free online jigsaw games, curated by puzzlesplan experts.",
        category: "Puzzlesplan . Jigsaw Games . Free Puzzles",
        image: "./images/Freezenova5.jpeg",
    },
    {
        id: 10,
        Details: { Author: "Puzzles Plan", Released: "September 2025", Credits: "Images from puzzlesplan website" },
        title: "Puzzlesplan Presents Freezenova Games",
        description: "Play the most engaging Freezenova jigsaw puzzles right on puzzlesplan.",
        category: "Puzzlesplan . Freezenova . Puzzle Fun",
        image: "./images/Freezenova6.jpeg",
    },
    {
        id: 11,
        Details: { Author: "Puzzles Plan", Released: "September 2025", Credits: "Images from puzzlesplan website" },
        title: "Explore Free Online Puzzles on Puzzlesplan",
        description: "Join thousands playing online puzzle games at puzzlesplan with fun challenges.",
        category: "Puzzlesplan . Online Puzzles . Game Hub",
        image: "./images/Freezenova7.jpeg",
    },
    {
        id: 12,
        Details: { Author: "Puzzles Plan", Released: "September 2025", Credits: "Images from puzzlesplan website" },
        title: "Online Puzzle Games by Puzzlesplan",
        description: "Solve relaxing and challenging jigsaw puzzles from puzzlesplan’s top selections.",
        category: "Puzzlesplan . Online Puzzles . Relax & Play",
        image: "./images/Freezenova8.jpeg",
    },
];

export default Blogsdb;
